### PR TITLE
examples: add 'nxt-screen'

### PR DESCRIPTION
**Pull request by JohSchneider**
utility that reads out the framebuffer of an USB-connected NXT, and uses pygame to display it's content on-screen

might be handy for owners of a NXT with "broken" display, wanting to access settings like Bluetooth, pairing, ...

### CODE REVIEW

**Comment by schodet** [comment]
Nice, this remind me of a script I made a long time ago: https://ni.fr.eu.org/lego/nxt_screenshot/

Why the beep?

**Comment by JohSchneider** [comment]
> Why the beep?

it's easier to tell a 10year old that he has to wait for a beep or two between button presses; than explain to him that the display refresh-rate is slow (to avoid interfering with the NXT too much) : )

**Comment by schodet** [comment]
OK, good point :)

**Comment by JohSchneider** [comment]
thanks for merging!

**Pull request merged**
